<?php

namespace App\Console\Commands;

use App\Engines\DTO\SliceParams;
use App\Engines\Slicer\OrcaSlicer;
use App\Models\ModelFile;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;

/**
 * Slices the given model files with OrcaSlicer itself (no cache) one at a time and N at a time, and prints the
 * seconds, the steps, grams, minutes and a hash of the G-code without its date line: the same hash before and after
 * a change of our code means the same print. Reads the files, writes nothing but temporary G-code.
 *
 *   php artisan matplace:perf-bench <uuid> <uuid> … --parallel=1,3
 */
class PerfBench extends Command
{
    protected $signature = 'matplace:perf-bench {files?* : uuids of model files} {--parallel=1,3 : how many slices at once, a list} {--material=PLA} {--quality=standard} {--one= : (internal) slice one file and print JSON}';

    protected $description = 'Slice sample models with OrcaSlicer, alone and several at once: seconds per step and a G-code hash';

    public function handle(): int
    {
        if ($one = $this->option('one')) {
            $this->line(json_encode($this->sliceOne($one)));

            return self::SUCCESS;
        }
        $uuids = (array) $this->argument('files');
        if (! $uuids) {
            $this->error('Give uuids of model files.');

            return self::FAILURE;
        }
        foreach (array_map('intval', explode(',', (string) $this->option('parallel'))) as $n) {
            $n = max(1, $n);
            $this->newLine();
            $this->info("{$n} at once");
            $rows = [];
            $started = microtime(true);
            foreach (array_chunk($uuids, $n) as $group) {
                $results = Process::pool(function ($pool) use ($group) {
                    foreach ($group as $uuid) {
                        $pool->timeout(1200)->command([PHP_BINARY, base_path('artisan'), 'matplace:perf-bench', '--one='.$uuid,
                            '--material='.$this->option('material'), '--quality='.$this->option('quality')]);
                    }
                })->start()->wait();
                foreach ($group as $i => $uuid) {
                    $r = json_decode(trim((string) $results[$i]->output()), true) ?: ['error' => trim($results[$i]->errorOutput())];
                    $rows[] = [substr($uuid, 0, 8), $r['triangles'] ?? '', $r['seconds'] ?? '', $r['timings']['mesh_s'] ?? '', $r['timings']['slice1_s'] ?? '',
                        $r['timings']['slice2_s'] ?? '', $r['timings']['parse_s'] ?? '', $r['grams'] ?? '', $r['minutes'] ?? '', $r['gcode'] ?? mb_substr($r['error'] ?? '', 0, 60)];
                }
            }
            $this->table(['file', 'triangles', 'total s', 'mesh s', 'slice1 s', 'slice2 s', 'parse s', 'g', 'min', 'G-code (no date)'], $rows);
            $this->line(sprintf('all %d files: %.1f s', count($uuids), microtime(true) - $started));
        }

        return self::SUCCESS;
    }

    private function sliceOne(string $uuid): array
    {
        $file = ModelFile::where('uuid', $uuid)->firstOrFail();
        $orca = new OrcaSlicer(config('engines.orca'));
        $params = new SliceParams((string) $this->option('material'), (string) $this->option('quality'), 15, null, treeSupports: $file->wantsTreeSupports(), keepGcode: true);
        $start = microtime(true);
        $r = $orca->slice((string) $file->absoluteStlPath(), $params);
        $seconds = round(microtime(true) - $start, 2);
        $hash = hash_init('sha256');
        $fh = fopen((string) $r->gcodePath, 'rb');
        while (($line = fgets($fh)) !== false) {
            if (! str_starts_with($line, '; generated by')) {
                hash_update($hash, $line);
            }
        }
        fclose($fh);
        File::delete((string) $r->gcodePath);

        return ['seconds' => $seconds, 'triangles' => $file->triangles, 'timings' => $r->timings, 'grams' => $r->grams, 'minutes' => $r->minutes,
            'gcode' => substr(hash_final($hash), 0, 16)];
    }
}
