# Adds step-4 (inquiries, offers, chat, mails) translation keys to cs/en/es. Run: python scripts/add_lang_inquiry.py
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")

K = {
    "printer.nav.inquiries": ("Poptávky", "Inquiries", "Solicitudes"),
    "inquiry.title": ("Poptávka", "Inquiry", "Solicitud"),
    "inquiry.pcs": ("ks", "pcs", "uds."),
    "inquiry.error": ("Poptávku se nepodařilo odeslat. Zkontroluj e-mail a PSČ.", "Could not send the inquiry. Check the e-mail and postcode.", "No se pudo enviar la solicitud. Revisa el correo y el código postal."),
    "inquiry.wait_precise": ("Počkej na přesnou cenu, pak můžeš poptat výrobu.", "Wait for the exact price, then you can request production.", "Espera al precio exacto y luego podrás solicitar la fabricación."),
    "inquiry.form.title": ("Chci to vyrobit", "Make it for me", "Quiero fabricarlo"),
    "inquiry.form.hint": ("Pošleme model tiskařům v okolí, kteří tisknou tenhle materiál. Ozvou se s cenou, vybereš si.", "We send the model to nearby printers who print this material. They reply with a price, you choose.", "Enviamos el modelo a impresores cercanos que imprimen este material. Responden con un precio y tú eliges."),
    "inquiry.form.wanted_by": ("Kdy to potřebuješ", "When do you need it", "Para cuándo lo necesitas"),
    "inquiry.form.note": ("Poznámka pro tiskaře (barva, k čemu to je…)", "Note for the printer (colour, purpose…)", "Nota para el impresor (color, uso…)"),
    "inquiry.form.submit": ("Poslat tiskařům", "Send to printers", "Enviar a impresores"),
    "inquiry.form.promise": ("Zdarma, bez provize. Domluvíte se a zaplatíte přímo tiskaři.", "Free, no commission. You arrange and pay the printer directly.", "Gratis, sin comisión. Te pones de acuerdo y pagas directamente al impresor."),
    "inquiry.delivery.any": ("Doručení: je mi to jedno", "Delivery: either way", "Entrega: me da igual"),
    "inquiry.delivery.pickup": ("Osobní odběr", "Pickup", "Recogida en persona"),
    "inquiry.delivery.shipping": ("Poslat poštou", "Shipping", "Envío"),
    "inquiry.status.pending": ("čeká na ověření e-mailu", "awaiting e-mail verification", "esperando verificación del correo"),
    "inquiry.status.open": ("rozesláno tiskařům", "sent to printers", "enviada a impresores"),
    "inquiry.status.offered": ("máš nabídky", "offers received", "tienes ofertas"),
    "inquiry.status.accepted": ("domluveno", "agreed", "acordada"),
    "inquiry.status.done": ("hotovo", "done", "hecha"),
    "inquiry.status.cancelled": ("zrušeno", "cancelled", "cancelada"),
    "inquiry.status.expired": ("vypršelo", "expired", "caducada"),
    "inquiry.pending_hint": ("Poslali jsme ti e-mail na :email. Klikni na odkaz v něm a poptávka se rozešle tiskařům.", "We sent an e-mail to :email. Click the link in it and the inquiry goes out to printers.", "Te hemos enviado un correo a :email. Haz clic en el enlace y la solicitud se enviará a los impresores."),
    "inquiry.verified": ("E-mail ověřen, poptávka jde tiskařům.", "E-mail verified, the inquiry is on its way to printers.", "Correo verificado, la solicitud va a los impresores."),
    "inquiry.verify_failed": ("Odkaz neplatí.", "The link is not valid.", "El enlace no es válido."),
    "inquiry.sent_to": ("Posláno :n tiskařům", "Sent to :n printers", "Enviado a :n impresores"),
    "inquiry.open_calc": ("otevřít kalkulaci", "open calculation", "abrir cálculo"),
    "inquiry.cancel": ("Zrušit poptávku", "Cancel inquiry", "Cancelar solicitud"),
    "inquiry.offers": ("Nabídky", "Offers", "Ofertas"),
    "inquiry.no_offers_yet": ("Zatím žádná nabídka. Tiskaři obvykle odpoví do 24 hodin; dáme ti vědět e-mailem.", "No offers yet. Printers usually reply within 24 hours; we will e-mail you.", "Todavía no hay ofertas. Los impresores suelen responder en 24 horas; te avisaremos por correo."),
    "inquiry.accept": ("Přijmout nabídku", "Accept offer", "Aceptar oferta"),
    "inquiry.you_accepted": ("Přijato", "Accepted", "Aceptada"),
    "inquiry.accepted_status": ("Nabídka přijata. Tiskař má tvůj kontakt, dohodněte se v chatu na platbě a předání.", "Offer accepted. The printer has your contact; agree on payment and handover in the chat.", "Oferta aceptada. El impresor tiene tu contacto; acordad el pago y la entrega en el chat."),
    "inquiry.done_hint": ("Až budeš mít výtisk v ruce, označ poptávku jako hotovou a ohodnoť tiskaře.", "Once you have the print, mark the inquiry as done and rate the printer.", "Cuando tengas la pieza, marca la solicitud como hecha y valora al impresor."),
    "inquiry.mark_done": ("Mám to, hotovo", "Got it, done", "Ya lo tengo, hecho"),
    "inquiry.done_status": ("Hotovo. Díky, ohodnoť prosím tiskaře.", "Done. Thanks, please rate the printer.", "Hecho. Gracias, valora al impresor."),
    "inquiry.cancelled_status": ("Poptávka zrušena.", "Inquiry cancelled.", "Solicitud cancelada."),
    "inquiry.rate_title": ("Jak to dopadlo s :printer?", "How did it go with :printer?", "¿Qué tal con :printer?"),
    "inquiry.rate_comment": ("Pár slov (nepovinné)", "A few words (optional)", "Unas palabras (opcional)"),
    "inquiry.rate_submit": ("Odeslat hodnocení", "Send rating", "Enviar valoración"),
    "inquiry.rated": ("Díky za hodnocení.", "Thanks for the rating.", "Gracias por la valoración."),
    "inquiry.promise": ("matplace vás jen spojil. Platba a předání jsou mezi tebou a tiskařem, nebereme provize.", "matplace only connected you. Payment and handover are between you and the printer; we take no commission.", "matplace solo os ha conectado. El pago y la entrega son entre tú y el impresor; no cobramos comisión."),
    "inquiry.printer_hint": ("Poptávky vybrané podle tvých materiálů, plochy a vzdálenosti. Cena je předvyplněná z tvého ceníku, uprav ji podle sebe.", "Inquiries matched to your materials, bed size and distance. The price is prefilled from your price list; adjust as you like.", "Solicitudes según tus materiales, cama y distancia. El precio viene de tu tarifa; ajústalo como quieras."),
    "inquiry.none_for_you": ("Zatím žádná poptávka. Zkontroluj, že máš vyplněné materiály, ceny a PSČ.", "No inquiries yet. Check that materials, prices and postcode are filled in.", "Aún no hay solicitudes. Comprueba materiales, precios y código postal."),
    "inquiry.wanted_by": ("do", "by", "para"),
    "inquiry.declined_status": ("odmítnuto", "declined", "rechazada"),
    "inquiry.rough_only": ("Jen hrubý odhad (přesný slice nebyl k dispozici).", "Rough estimate only (no precise slice available).", "Solo estimación aproximada (sin corte preciso)."),
    "inquiry.your_offer": ("Tvoje nabídka", "Your offer", "Tu oferta"),
    "inquiry.accepted_printer": ("Zákazník přijal tvou nabídku. Kontakt: :name, :email, :phone. Domluvte se v chatu na platbě a předání.", "The customer accepted your offer. Contact: :name, :email, :phone. Agree on payment and handover in the chat.", "El cliente aceptó tu oferta. Contacto: :name, :email, :phone. Acordad el pago y la entrega en el chat."),
    "inquiry.you_declined": ("Tuhle poptávku jsi odmítl.", "You declined this inquiry.", "Has rechazado esta solicitud."),
    "inquiry.make_offer": ("Poslat nabídku", "Send an offer", "Enviar oferta"),
    "inquiry.auto_price_hint": ("Podle tvého ceníku", "From your price list", "Según tu tarifa"),
    "inquiry.price_total": ("Cena celkem", "Total price", "Precio total"),
    "inquiry.offer_note": ("Zpráva zákazníkovi (barva, termín, odběr…)", "Message to the customer (colour, timing, pickup…)", "Mensaje al cliente (color, plazo, recogida…)"),
    "inquiry.send_offer": ("Odeslat nabídku", "Send offer", "Enviar oferta"),
    "inquiry.decline": ("Tohle nechci tisknout", "Not for me", "No quiero imprimirlo"),
    "inquiry.closed_for_offers": ("Poptávka už nepřijímá nabídky.", "This inquiry no longer accepts offers.", "Esta solicitud ya no acepta ofertas."),
    "inquiry.offer_sent": ("Nabídka odeslána zákazníkovi.", "Offer sent to the customer.", "Oferta enviada al cliente."),
    "inquiry.chat.placeholder": ("Napiš zprávu…", "Write a message…", "Escribe un mensaje…"),
    "inquiry.chat.send": ("Odeslat", "Send", "Enviar"),
    "inquiry.chat.attach": ("Přiložit soubor nebo fotku", "Attach a file or photo", "Adjuntar archivo o foto"),
    "inquiry.sys.offer": ("Tiskař poslal nabídku: :price Kč.", "The printer sent an offer: :price CZK.", "El impresor envió una oferta: :price CZK."),
    "inquiry.sys.accepted": ("Zákazník nabídku přijal. Domluvte se na platbě a předání.", "The customer accepted the offer. Agree on payment and handover.", "El cliente aceptó la oferta. Acordad el pago y la entrega."),
    "inquiry.sys.lost": ("Zákazník vybral jinou nabídku. Díky za tvůj čas.", "The customer chose another offer. Thanks for your time.", "El cliente eligió otra oferta. Gracias por tu tiempo."),
    "quote.line.adjust": ("Úprava ceny", "Price adjustment", "Ajuste de precio"),
    "inquiry.mail.footer": ("matplace vás jen spojuje. Platba a předání jsou přímo mezi vámi, bez provize.", "matplace only connects you. Payment and handover are directly between you, no commission.", "matplace solo os conecta. El pago y la entrega son directamente entre vosotros, sin comisión."),
    "inquiry.mail.verify.subject": ("Potvrď svou poptávku na matplace", "Confirm your matplace inquiry", "Confirma tu solicitud en matplace"),
    "inquiry.mail.verify.heading": ("Ještě jedno kliknutí", "One more click", "Un clic más"),
    "inquiry.mail.verify.body": ("Potvrď, že poptávka na :model (:material, :quantity ks) je tvoje. Pak ji pošleme tiskařům v okolí :city.", "Confirm that the inquiry for :model (:material, :quantity pcs) is yours. Then we send it to printers near :city.", "Confirma que la solicitud de :model (:material, :quantity uds.) es tuya. Después la enviamos a impresores cerca de :city."),
    "inquiry.mail.verify.button": ("Potvrdit a rozeslat", "Confirm and send", "Confirmar y enviar"),
    "inquiry.mail.new_inquiry.subject": ("Nová poptávka: :model (:material, :quantity ks)", "New inquiry: :model (:material, :quantity pcs)", "Nueva solicitud: :model (:material, :quantity uds.)"),
    "inquiry.mail.new_inquiry.heading": ("Někdo poblíž potřebuje vytisknout :model", "Someone nearby needs :model printed", "Alguien cerca necesita imprimir :model"),
    "inquiry.mail.new_inquiry.body": (":material, :quantity ks, z :city (:distance km). Podle tvého ceníku to vychází na :price Kč. Otevři poptávku, zkontroluj model a pošli nabídku, nebo ji odmítni.", ":material, :quantity pcs, from :city (:distance km). Your price list gives :price CZK. Open the inquiry, check the model and send an offer, or decline.", ":material, :quantity uds., desde :city (:distance km). Según tu tarifa sale a :price CZK. Abre la solicitud, revisa el modelo y envía una oferta, o recházala."),
    "inquiry.mail.new_inquiry.button": ("Otevřít poptávku", "Open inquiry", "Abrir solicitud"),
    "inquiry.mail.new_offer.subject": ("Nabídka od :printer: :price Kč", "Offer from :printer: :price CZK", "Oferta de :printer: :price CZK"),
    "inquiry.mail.new_offer.heading": ("Máš nabídku", "You have an offer", "Tienes una oferta"),
    "inquiry.mail.new_offer.body": (":printer nabízí vytisknout :model za :price Kč. Podívej se, porovnej s ostatními a přijmi tu, která ti sedí.", ":printer offers to print :model for :price CZK. Have a look, compare with others and accept the one that suits you.", ":printer ofrece imprimir :model por :price CZK. Míralo, compara con otras y acepta la que te convenga."),
    "inquiry.mail.new_offer.button": ("Zobrazit nabídky", "View offers", "Ver ofertas"),
    "inquiry.mail.accepted.subject": ("Zákazník přijal tvou nabídku (:model)", "Customer accepted your offer (:model)", "El cliente aceptó tu oferta (:model)"),
    "inquiry.mail.accepted.heading": ("Máš zakázku 🎉", "You have a job 🎉", "Tienes un encargo 🎉"),
    "inquiry.mail.accepted.body": (":client přijal nabídku :price Kč na :model. Domluvte se v chatu na platbě a předání.", ":client accepted your :price CZK offer for :model. Agree on payment and handover in the chat.", ":client aceptó tu oferta de :price CZK por :model. Acordad el pago y la entrega en el chat."),
    "inquiry.mail.accepted.button": ("Otevřít zakázku", "Open job", "Abrir encargo"),
    "inquiry.mail.lost.subject": ("Zákazník vybral jinou nabídku (:model)", "Customer chose another offer (:model)", "El cliente eligió otra oferta (:model)"),
    "inquiry.mail.lost.heading": ("Tentokrát ne", "Not this time", "Esta vez no"),
    "inquiry.mail.lost.body": ("Zákazník si u :model vybral jinou nabídku. Díky za rychlou odpověď, další poptávka přijde.", "The customer chose another offer for :model. Thanks for the quick reply, the next inquiry will come.", "El cliente eligió otra oferta para :model. Gracias por responder rápido, llegará la próxima."),
    "inquiry.mail.lost.button": ("Zobrazit poptávku", "View inquiry", "Ver solicitud"),
    "inquiry.mail.cancelled.subject": ("Poptávka zrušena (:model)", "Inquiry cancelled (:model)", "Solicitud cancelada (:model)"),
    "inquiry.mail.cancelled.heading": ("Zákazník poptávku zrušil", "The customer cancelled the inquiry", "El cliente canceló la solicitud"),
    "inquiry.mail.cancelled.body": ("Poptávka na :model už neplatí. Díky za tvou nabídku.", "The inquiry for :model is no longer valid. Thanks for your offer.", "La solicitud de :model ya no es válida. Gracias por tu oferta."),
    "inquiry.mail.cancelled.button": ("Zobrazit poptávku", "View inquiry", "Ver solicitud"),
    "inquiry.mail.msg_customer.subject": ("Nová zpráva od :printer", "New message from :printer", "Nuevo mensaje de :printer"),
    "inquiry.mail.msg_customer.heading": ("Tiskař ti píše", "The printer wrote to you", "El impresor te ha escrito"),
    "inquiry.mail.msg_customer.body": (":printer poslal zprávu k poptávce na :model.", ":printer sent a message about :model.", ":printer envió un mensaje sobre :model."),
    "inquiry.mail.msg_customer.button": ("Otevřít chat", "Open chat", "Abrir chat"),
    "inquiry.mail.msg_printer.subject": ("Nová zpráva od zákazníka (:model)", "New message from the customer (:model)", "Nuevo mensaje del cliente (:model)"),
    "inquiry.mail.msg_printer.heading": ("Zákazník ti píše", "The customer wrote to you", "El cliente te ha escrito"),
    "inquiry.mail.msg_printer.body": (":client poslal zprávu k poptávce na :model.", ":client sent a message about :model.", ":client envió un mensaje sobre :model."),
    "inquiry.mail.msg_printer.button": ("Otevřít chat", "Open chat", "Abrir chat"),
}

for i, lang in enumerate(("cs", "en", "es")):
    p = os.path.join(ROOT, "lang", f"{lang}.json")
    with open(p, encoding="utf-8") as f:
        d = json.load(f)
    for k, v in K.items():
        d[k] = v[i]
    with open(p, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=4)
        f.write("\n")
    print(lang, len(d))
