# Adds step-2 translation keys to lang/cs.json and lang/en.json (idempotent). Run: python scripts/add_lang_keys.py
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")

cs = {
    "nav.account": "Můj účet", "nav.login": "Přihlásit", "nav.for_printers": "Pro tiskaře", "nav.printer": "Tiskař",
    "calc.profile.mine": "Moje cena", "calc.others_from": "ostatní tiskaři od :n (:c)", "calc.printers_count": "ceny :c skutečných tiskařů",
    "account.title": "Můj účet", "account.hello": "Ahoj, :name", "account.edit_profile": "Upravit profil", "account.profile": "Profil",
    "account.saved": "Uloženo.", "account.role_enabled": "Role zapnuta.", "account.role_disabled": "Role vypnuta, data zůstávají.",
    "account.role.printer": "Mám tiskárnu", "account.role.printer.hint": "Kalkulačka s vlastními cenami a nabídky pro klienty.",
    "account.role.designer": "Umím modelovat", "account.role.designer.hint": "Portfolio, licence a zakázky na dopracování.",
    "account.designer_soon": "Nástroje pro designéry připravujeme.", "account.open_printer": "Otevřít nástroje tiskaře",
    "account.on": "Zapnuto", "account.off": "Zapnout", "account.calculations": "Moje kalkulace", "account.no_calculations": "Zatím žádné.",
    "account.start": "Nahrát první model →", "account.phone": "Telefon", "account.zip": "PSČ", "account.city": "Obec",
    "account.location_hint": "Podle PSČ najdeme tiskaře v okolí. Přesnou adresu nepotřebujeme.", "account.locale": "Jazyk",
    "account.notify_email": "Posílat e-mailem, když se něco stane", "account.change_password": "Změnit heslo", "account.save": "Uložit",
    "account.role_required.printer": "Nejdřív si v účtu zapni „Mám tiskárnu“.", "account.role_required.designer": "Nejdřív si v účtu zapni „Umím modelovat“.",
    "printer.title": "Tiskař", "printer.welcome": "Vítej! Nastav si ceny a materiály, zabere to dvě minuty.",
    "printer.profile_saved": "Profil a ceny uloženy.", "printer.nav.home": "Přehled", "printer.nav.calculator": "Kalkulačka",
    "printer.nav.quotes": "Nabídky", "printer.nav.profile": "Ceny a profil", "printer.nav.account": "Účet",
    "printer.checklist.title": "Než začneš posílat nabídky", "printer.checklist.materials": "vyber materiály, které tiskneš",
    "printer.checklist.pricing": "nastav cenu za hodinu a za gram", "printer.checklist.machine": "doplň tiskárnu (rozměr plochy)",
    "printer.checklist.contact": "doplň kontakt na nabídky", "printer.checklist.location": "doplň PSČ, ať tě najdou zákazníci z okolí",
    "printer.checklist.go": "Doplnit →", "printer.calc.title": "Kalkulačka", "printer.calc.hint": "Nahraj soubor klienta, uvidíš svou cenu, jedním tlačítkem pošleš nabídku.",
    "printer.calc.lead": "STL, 3MF, OBJ nebo STEP → tvoje cena podle tvého ceníku → nabídka PDF a odkaz.", "printer.calc.create_quote": "Vytvořit nabídku",
    "printer.profile.title": "Ceny a profil", "printer.profile.hint": "Pět polí a hotovo. Zbytek pod „Více“.",
    "printer.profile.pricing": "Kolik účtuješ", "printer.profile.pricing_hint": "Cena = gramy × Kč/g + hodiny × Kč/h + příprava. Stejné ceny uvidí zákazníci u svých modelů.",
    "printer.profile.more": "Více nastavení", "printer.profile.identity": "Kdo jsi (na nabídky)", "printer.profile.machine": "Tiskárna", "printer.profile.save": "Uložit ceny a profil",
    "printer.f.hourly_rate": "Cena za hodinu stroje", "printer.f.price_per_gram": "Cena za gram", "printer.f.setup_fee": "Příprava zakázky",
    "printer.f.margin_pct": "Marže", "printer.f.lead_time_days": "Dodací lhůta", "printer.f.materials": "Materiály, které tiskneš",
    "printer.f.materials_hint": "Volitelně vlastní cena za gram u materiálu (jinak platí obecná).", "printer.f.min_price": "Minimální cena zakázky",
    "printer.f.express_pct": "Expres příplatek", "printer.f.qty_discounts": "Slevy za počet kusů", "printer.f.qty_discounts_hint": "od kusů : procenta, např. 5:10, 20:20",
    "printer.f.display_name": "Jméno na nabídkách", "printer.f.company": "Firma", "printer.f.logo": "Logo", "printer.f.contact_email": "E-mail na nabídkách",
    "printer.f.contact_phone": "Telefon", "printer.f.pickup_address": "Adresa osobního odběru", "printer.f.bio": "Krátce o tobě",
    "printer.f.delivery": "Doručení", "printer.delivery.pickup": "osobní odběr", "printer.delivery.zasilkovna": "Zásilkovna", "printer.delivery.courier": "kurýr",
    "printer.f.capacity": "Kapacita", "printer.capacity.open": "beru zakázky", "printer.capacity.busy": "mám plno, jen nespěchající", "printer.capacity.paused": "pauza",
    "printer.f.machine_name": "Tiskárna", "printer.f.machine_count": "Počet", "printer.f.technology": "Technologie", "printer.f.bed": "Tisková plocha",
    "printer.f.visible": "Zobrazovat mou cenu zákazníkům u jejich modelů", "printer.quotes.recent": "Poslední nabídky", "printer.quotes.all": "Všechny", "printer.quotes.none": "Zatím žádná nabídka. Začni v kalkulačce.",
    "quote.created": "Nabídka založena, doplň klienta a zkontroluj řádky.", "quote.saved": "Nabídka uložena.", "quote.sent_mail": "Nabídka odeslána na :email.",
    "quote.sent_link": "Nabídka je odeslaná, pošli klientovi odkaz.", "quote.duplicated": "Kopie nabídky vytvořena.", "quote.new_empty": "Nová prázdná nabídka",
    "quote.no_client": "bez klienta", "quote.client_name": "Klient", "quote.client_email": "E-mail klienta", "quote.title": "Název / model",
    "quote.note": "Poznámka pro klienta", "quote.valid_until": "Platnost do", "quote.lead_time": "Dodání", "quote.days_short": "dní", "quote.from_calc": "Z kalkulace",
    "quote.save": "Uložit", "quote.send_mail": "Odeslat klientovi e-mailem", "quote.send_link": "Označit jako odeslanou a získat odkaz",
    "quote.send_hint": "Odeslání vygeneruje PDF a online verzi s tlačítkem „Přijímám“.", "quote.add_line": "přidat řádek", "quote.repeat": "Opakovat",
    "quote.open_link": "Otevřít odkaz", "quote.number": "Číslo", "quote.date": "Datum", "quote.client": "Klient", "quote.model": "Model",
    "quote.line.material": "Materiál :material", "quote.line.time": "Čas stroje", "quote.line.setup": "Příprava zakázky", "quote.line.royalty": "Autorský poplatek",
    "quote.line.discount": "Množstevní sleva :pct %", "quote.line.margin": "Marže", "quote.line.rounding": "Zaokrouhlení / minimum", "quote.line.print": "3D tisk",
    "quote.pdf.title": "Nabídka", "quote.pdf.item": "Položka", "quote.pdf.qty": "Ks", "quote.pdf.unit": "Cena/ks", "quote.pdf.total": "Celkem", "quote.pdf.sum": "Celkem k úhradě",
    "quote.pdf.online": "Online verze s 3D náhledem a přijetím", "quote.pdf.footer": "Nabídka vytvořena na matplace.com. Platba a dodání probíhá přímo mezi tiskařem a klientem, matplace nebere provize.",
    "quote.btn.accept": "Přijímám nabídku", "quote.btn.decline": "Odmítnout", "quote.status.draft": "koncept", "quote.status.sent": "odesláno", "quote.status.viewed": "zobrazeno",
    "quote.status.accepted": "přijato", "quote.status.declined": "odmítnuto", "quote.status.expired": "vypršelo", "quote.accepted_thanks": "Díky! Tiskař dostal zprávu a ozve se ti.",
    "quote.declined_thanks": "Rozumíme, nabídka je odmítnutá.", "quote.public.footer": "Tuhle nabídku vytvořil tiskař na matplace.com. Platíš přímo jemu, my nebereme provize.",
    "quote.mail.subject": "Nabídka :number od :printer", "quote.mail.heading": "Nabídka od :printer", "quote.mail.intro": "Posíláme nabídku :number na :total :currency. V příloze je PDF, online verze má 3D náhled a tlačítko pro přijetí.",
    "quote.mail.button": "Zobrazit nabídku", "quote.mail.footer": "Odpovědí na tento e-mail píšeš přímo tiskaři.",
    "quote.mail.accepted_subject": "Klient přijal nabídku :number", "quote.mail.accepted_heading": "Nabídka přijata 🎉", "quote.mail.accepted_intro": "Nabídku :number (:client) za :total Kč klient právě přijal. Domluv s ním platbu a dodání.",
    "quote.mail.accepted_button": "Otevřít nabídku", "quote.mail.accepted_footer": "matplace vás jen spojil; platba a dodání jsou mezi vámi.",
}

en = {
    "nav.account": "My account", "nav.login": "Log in", "nav.for_printers": "For printers", "nav.printer": "Printer",
    "calc.profile.mine": "My price", "calc.others_from": "other printers from :n (:c)", "calc.printers_count": "prices of :c real printers",
    "account.title": "My account", "account.hello": "Hi, :name", "account.edit_profile": "Edit profile", "account.profile": "Profile",
    "account.saved": "Saved.", "account.role_enabled": "Role enabled.", "account.role_disabled": "Role disabled, data kept.",
    "account.role.printer": "I own a printer", "account.role.printer.hint": "Calculator with your own prices and quotes for clients.",
    "account.role.designer": "I can model", "account.role.designer.hint": "Portfolio, licences and design jobs.",
    "account.designer_soon": "Designer tools are coming soon.", "account.open_printer": "Open printer tools",
    "account.on": "On", "account.off": "Turn on", "account.calculations": "My calculations", "account.no_calculations": "Nothing yet.",
    "account.start": "Upload a first model →", "account.phone": "Phone", "account.zip": "Postcode", "account.city": "Town",
    "account.location_hint": "We use the postcode to find printers nearby. No exact address needed.", "account.locale": "Language",
    "account.notify_email": "E-mail me when something happens", "account.change_password": "Change password", "account.save": "Save",
    "account.role_required.printer": "Turn on “I own a printer” in your account first.", "account.role_required.designer": "Turn on “I can model” in your account first.",
    "printer.title": "Printer", "printer.welcome": "Welcome! Set your prices and materials, it takes two minutes.",
    "printer.profile_saved": "Profile and prices saved.", "printer.nav.home": "Overview", "printer.nav.calculator": "Calculator",
    "printer.nav.quotes": "Quotes", "printer.nav.profile": "Prices & profile", "printer.nav.account": "Account",
    "printer.checklist.title": "Before you send quotes", "printer.checklist.materials": "pick the materials you print",
    "printer.checklist.pricing": "set your hourly and per-gram price", "printer.checklist.machine": "add your printer (bed size)",
    "printer.checklist.contact": "add a contact for quotes", "printer.checklist.location": "add your postcode so nearby customers find you",
    "printer.checklist.go": "Complete →", "printer.calc.title": "Calculator", "printer.calc.hint": "Upload a client file, see your price, send a quote with one button.",
    "printer.calc.lead": "STL, 3MF, OBJ or STEP → your price from your price list → PDF quote and link.", "printer.calc.create_quote": "Create quote",
    "printer.profile.title": "Prices & profile", "printer.profile.hint": "Five fields and done. The rest is under “More”.",
    "printer.profile.pricing": "What you charge", "printer.profile.pricing_hint": "Price = grams × CZK/g + hours × CZK/h + setup. Customers see the same prices on their models.",
    "printer.profile.more": "More settings", "printer.profile.identity": "Who you are (on quotes)", "printer.profile.machine": "Printer", "printer.profile.save": "Save prices and profile",
    "printer.f.hourly_rate": "Machine hour rate", "printer.f.price_per_gram": "Price per gram", "printer.f.setup_fee": "Job setup fee",
    "printer.f.margin_pct": "Margin", "printer.f.lead_time_days": "Lead time", "printer.f.materials": "Materials you print",
    "printer.f.materials_hint": "Optional per-material gram price (otherwise the general one applies).", "printer.f.min_price": "Minimum order price",
    "printer.f.express_pct": "Express surcharge", "printer.f.qty_discounts": "Quantity discounts", "printer.f.qty_discounts_hint": "from pieces : percent, e.g. 5:10, 20:20",
    "printer.f.display_name": "Name on quotes", "printer.f.company": "Company", "printer.f.logo": "Logo", "printer.f.contact_email": "E-mail on quotes",
    "printer.f.contact_phone": "Phone", "printer.f.pickup_address": "Pickup address", "printer.f.bio": "About you",
    "printer.f.delivery": "Delivery", "printer.delivery.pickup": "pickup", "printer.delivery.zasilkovna": "Zásilkovna", "printer.delivery.courier": "courier",
    "printer.f.capacity": "Capacity", "printer.capacity.open": "taking orders", "printer.capacity.busy": "full, non-urgent only", "printer.capacity.paused": "paused",
    "printer.f.machine_name": "Printer", "printer.f.machine_count": "Count", "printer.f.technology": "Technology", "printer.f.bed": "Build volume",
    "printer.f.visible": "Show my price to customers on their models", "printer.quotes.recent": "Recent quotes", "printer.quotes.all": "All", "printer.quotes.none": "No quotes yet. Start in the calculator.",
    "quote.created": "Quote created, add the client and check the lines.", "quote.saved": "Quote saved.", "quote.sent_mail": "Quote sent to :email.",
    "quote.sent_link": "Quote is sent, share the link with your client.", "quote.duplicated": "Quote copied.", "quote.new_empty": "New empty quote",
    "quote.no_client": "no client", "quote.client_name": "Client", "quote.client_email": "Client e-mail", "quote.title": "Title / model",
    "quote.note": "Note for the client", "quote.valid_until": "Valid until", "quote.lead_time": "Delivery", "quote.days_short": "days", "quote.from_calc": "From calculation",
    "quote.save": "Save", "quote.send_mail": "Send to client by e-mail", "quote.send_link": "Mark as sent and get the link",
    "quote.send_hint": "Sending generates the PDF and the online version with an Accept button.", "quote.add_line": "add line", "quote.repeat": "Repeat",
    "quote.open_link": "Open link", "quote.number": "Number", "quote.date": "Date", "quote.client": "Client", "quote.model": "Model",
    "quote.line.material": "Material :material", "quote.line.time": "Machine time", "quote.line.setup": "Job setup", "quote.line.royalty": "Designer royalty",
    "quote.line.discount": "Quantity discount :pct %", "quote.line.margin": "Margin", "quote.line.rounding": "Rounding / minimum", "quote.line.print": "3D print",
    "quote.pdf.title": "Quote", "quote.pdf.item": "Item", "quote.pdf.qty": "Qty", "quote.pdf.unit": "Unit price", "quote.pdf.total": "Total", "quote.pdf.sum": "Total due",
    "quote.pdf.online": "Online version with 3D preview and acceptance", "quote.pdf.footer": "Quote created on matplace.com. Payment and delivery happen directly between printer and client; matplace takes no commission.",
    "quote.btn.accept": "Accept quote", "quote.btn.decline": "Decline", "quote.status.draft": "draft", "quote.status.sent": "sent", "quote.status.viewed": "viewed",
    "quote.status.accepted": "accepted", "quote.status.declined": "declined", "quote.status.expired": "expired", "quote.accepted_thanks": "Thanks! The printer has been notified and will get in touch.",
    "quote.declined_thanks": "Understood, the quote is declined.", "quote.public.footer": "This quote was made by a printer on matplace.com. You pay them directly, we take no commission.",
    "quote.mail.subject": "Quote :number from :printer", "quote.mail.heading": "Quote from :printer", "quote.mail.intro": "Here is quote :number for :total :currency. The PDF is attached; the online version has a 3D preview and an accept button.",
    "quote.mail.button": "View quote", "quote.mail.footer": "Replying to this e-mail goes straight to the printer.",
    "quote.mail.accepted_subject": "Client accepted quote :number", "quote.mail.accepted_heading": "Quote accepted 🎉", "quote.mail.accepted_intro": "Your client just accepted quote :number (:client) for :total CZK. Arrange payment and delivery with them.",
    "quote.mail.accepted_button": "Open quote", "quote.mail.accepted_footer": "matplace only connected you; payment and delivery are between you.",
}

for lang, add in (("cs", cs), ("en", en)):
    p = os.path.join(ROOT, "lang", f"{lang}.json")
    with open(p, encoding="utf-8") as f:
        d = json.load(f)
    d.update(add)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=4)
        f.write("\n")
    print(lang, len(d))
