<?php

namespace App\Engines\Slicer;

use App\Domain\Calculation\RoughEstimator;
use App\Engines\Contracts\Slicer;
use App\Engines\DTO\Dimensions;
use App\Engines\DTO\SliceParams;
use App\Engines\DTO\SliceResult;
use App\Engines\Mesh\StlFile;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

/**
 * Deterministic slicer for tests and local development without OrcaSlicer.
 * Uses real geometry (volume, area) and the rough estimator, so numbers are plausible and repeatable.
 */
final class FakeSlicer implements Slicer
{
    public function __construct(private readonly RoughEstimator $rough) {}

    public function name(): string
    {
        return 'fake';
    }

    public function supportedFormats(): array
    {
        return ['stl'];
    }

    public function slice(string $meshPath, SliceParams $params): SliceResult
    {
        $stats = StlFile::stats($meshPath);
        $est = $this->rough->estimate(
            volumeMm3: $stats->volumeMm3,
            areaMm2: $stats->areaMm2,
            materialCode: $params->materialCode,
            quality: $params->quality,
            infillPercent: $params->infillPercent,
            supports: (bool) $params->supports,
            scale: $params->scale,
        );

        $grams = round($est['grams'] * 1.03, 1); // "precise" differs slightly from rough on purpose
        $minutes = (int) round($est['minutes'] * 0.97);
        $meters = round($grams / 1.24 / (M_PI * 0.875 ** 2), 2); // 1.75 mm PLA

        return new SliceResult(
            grams: $grams,
            minutes: $minutes,
            dims: $stats->bbox->scaled($params->scale),
            supportsUsed: (bool) $params->supports,
            gcodePath: $params->keepGcode ? $this->stubGcode($grams, $meters, $minutes) : null,
            warnings: [],
            raw: ['engine' => 'fake'],
            meters: $meters,
        );
    }

    /** The farm stores and ships the G-code, so the fake engine produces a file with the same header lines a real one has. */
    private function stubGcode(float $grams, float $meters, int $minutes): string
    {
        $path = rtrim((string) config('engines.orca.work_dir'), '/').'/gcode/'.Str::uuid().'.gcode';
        File::ensureDirectoryExists(dirname($path));
        File::put($path, "; generated by FakeSlicer\nG9111 bedTemp=55 extruderTemp=220\nM117\nT0\nG1 X10 Y10 F3000\n"
            .'; filament used [mm] = '.round($meters * 1000, 2)."\n; total filament used [g] = {$grams}\n"
            .'; estimated printing time (normal mode) = '.intdiv($minutes, 60).'h '.($minutes % 60)."m 0s\n");

        return $path;
    }

    public function measure(string $meshPath): Dimensions
    {
        return StlFile::stats($meshPath)->bbox;
    }
}
